// <auto-generated />
using System;
using DataAccessLibrary.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(FollowerDbContext))]
    [Migration("20220520125433_StatisticsAddedInit1")]
    partial class StatisticsAddedInit1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccessLibrary.Models.ChannelSnippet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsStared")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Statistic", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChannelSnippetId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubscriberCount")
                        .HasColumnType("int");

                    b.Property<int>("VideosCount")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.HasIndex("ChannelSnippetId");

                    b.ToTable("Statistic");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.Statistic", b =>
                {
                    b.HasOne("DataAccessLibrary.Models.ChannelSnippet", null)
                        .WithMany("Statistic")
                        .HasForeignKey("ChannelSnippetId");
                });

            modelBuilder.Entity("DataAccessLibrary.Models.ChannelSnippet", b =>
                {
                    b.Navigation("Statistic");
                });
#pragma warning restore 612, 618
        }
    }
}
